name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install required packages
        run: |
          sudo apt-get update && sudo apt-get install -y dnf
          sudo dnf check-update
          sudo dnf install -y gcc make kernel-devel
      - name: Build the module
        run: make
