name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install required packages
        run: >
          sudo apt-get update && sudo apt-get upgrade -y &&
          sudo apt-get install -y build-essential linux-headers-$(uname -r)
      - name: Build the module
        run: make
