name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install required packages
        run: >
          sudo apt update && sudo apt install -y
          build-essential gcc-14 linux-headers-$(uname -r)
      - name: Build and run the testing script
        run: sudo sh test/test_all.sh
